# This is a basic workflow to help you get started with Actions

name: Create Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Package deli file
        run: |
          mkdir Devyndamonster-PMCPete
          zip -r Devyndamonster-PMCPete/PMCPete.deli PMCPete
          cd deli
          zip -u ../Devyndamonster-PMCPete/PMCPete.deli *
          cd ..
          cp manifest.json Devyndamonster-PMCPete/
          cp icon.png Devyndamonster-PMCPete/
          cp README.md Devyndamonster-PMCPete/
          ls
          
        
      - name: Package files
        uses: actions/upload-artifact@v2
        with:
          name: PMCPeteRelease
          path: Devyndamonster-PMCPete
          
          
      
 
